# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName1: 'qserver:$(build.buildId)'
  imageName2: 'qsilo:$(build.buildId)'

steps:
- script: docker build -f ./Server/Dockerfile -t $(imageName1) .
  displayName: 'Server: docker build'
  workingDirectory: ./src

- script: docker build -f ./Silo.Host/Dockerfile -t $(imageName2) .
  displayName: 'Silo docker build'
  workingDirectory: ./src

- script: |
    export DOTNET_ROOT=$HOME/.dotnet/
    export PATH=$PATH:$HOME/.dotnet/tools
    dotnet tool install fake-cli -g
    fake build -t BuildElectron
  workingDirectory: ./src
  displayName: 'electron'
