# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'your-container-image-name:$(build.buildId)'

steps:
- script: docker build -f ./src/Server/Dockerfile -t $(imageName) .
  displayName: 'Server: docker build'

- script: docker build -f ./src/Silo.Host/Dockerfile -t $(imageName) .
  displayName: 'Silo docker build'

- script: |
    export DOTNET_ROOT=$HOME/.dotnet/
    export PATH=$PATH:$HOME/.dotnet/tools
    dotnet tool install fake-cli -g
    fake build -t BuildElectron

  displayName: 'electron'
