trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName1: 'qserver:$(build.buildId)'
  imageName2: 'qsilo:$(build.buildId)'

steps:
- script: docker build -f ./Server/Dockerfile -t $(imageName1) .
  displayName: 'Server: docker build'
  workingDirectory: ./src

- script: docker build -f ./Silo.Host/Dockerfile -t $(imageName2) .
  displayName: 'Silo docker build'
  workingDirectory: ./src

- script: |
    export PATH=$PATH:$HOME/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands
    dotnet tool install fake-cli -g
    fake build -t BuildElectron
  workingDirectory: ./src
  displayName: 'electron'
